CHRIS/CHRIS/Controllers/PayrollReportsController.cs
using CHRIS.ReportModels;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Text;
using CHRIS.Common;
using CHRIS.Services;
using Newtonsoft.Json;
using System.Data;
using System.Security.Cryptography.Xml;

namespace CHRIS.Controllers
{
    public class PayrollReportsController : Controller
    {
        #region PERIODIC REPORT FOR INC PROMOTION
        public IActionResult PeriodicReportForIncPromotion()
        {
            string message = "";
            try
            {

            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            finally
            {
                ViewBag.message = message;
            }
            return View();
        }
        [HttpPost]
        public IActionResult PeriodicReportForIncPromotion(string PRFI_BRANCH, DateTime? PRFI_FROM_DATE, DateTime? PRFI_TO_DATE)
        {
            string message = "";
            try
            {
                HttpResponseMessage file = new HttpResponseMessage();
                PY001Model entity = new PY001Model();
                entity.Branch = PRFI_BRANCH;
                if (PRFI_FROM_DATE != null)
                    entity.From_Date = Convert.ToDateTime(PRFI_FROM_DATE);
                else
                    entity.From_Date = null;
                if (PRFI_TO_DATE != null)
                    entity.To_Date = Convert.ToDateTime(PRFI_TO_DATE);
                else
                    entity.To_Date = null;
                var DomainName = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build().GetSection("CHRIS_REPORTING")["API_URL"];
                string BASE_URL = DomainName + "api/PayrollReporting/PeriodicReportForIncPromotion/";
                using (HttpClient clienFNREP08 = new HttpClient())
                {
                    using (HttpRequestMessage req310 = new HttpRequestMessage(HttpMethod.Post, BASE_URL))
                    {
                        req310.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                        string dataAsJson = System.Text.Json.JsonSerializer.Serialize(entity,
                        new JsonSerializerOptions() { WriteIndented = false });
                        message += dataAsJson + Environment.NewLine;
                        var content = new StringContent(dataAsJson, Encoding.UTF8, "application/json");
                        req310.Content = content;
                        req310.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                        HttpResponseMessage response = clienFNREP08.SendAsync(req310).Result;
                        int StatusCode = (int)response.StatusCode;
                        string StatusDesc = response.StatusCode.ToString();
                        if (StatusCode == 200)
                        {
                            file = response;
                            return File(file.Content.ReadAsByteArrayAsync().Result, "application/octet-stream", "PY001_" + DateTime.Now.ToString("dd_MM_yyyy") + ".pdf");
                        }
                        else
                        {
                            message = "Code : " + StatusCode + " | Description : " + StatusDesc;
                            return View();
                        }
                        //return responsse;
                    }
                }
            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            finally
            {
                ViewBag.message = message;
            }
            return View();
        }
        #endregion

        #region MONTHLY STAFF PAYMENT LISTINGS
        public IActionResult MonthlyStaffPaymentListings()
        {
            string message = "";
            try
            {

            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            finally
            {
                ViewBag.message = message;
            }
            return View();
        }
        [HttpPost]
        public IActionResult MonthlyStaffPaymentListings(string MSP_BRANCH, string MSP_SEGMENT, string MSP_CATEGORY, int? MSP_MONTH, int? MSP_YEAR, string MSP_FLAG)
        {
            string message = "";
            try
            {
                HttpResponseMessage file = new HttpResponseMessage();
                PY002Model entity = new PY002Model();
                entity.Branch = MSP_BRANCH;
                entity.Segment = MSP_SEGMENT;
                entity.Category = MSP_CATEGORY;
                if (MSP_MONTH != null)
                    entity.Month = Convert.ToInt32(MSP_MONTH);
                else
                    entity.Month = null;
                if (MSP_YEAR != null)
                    entity.Year = Convert.ToInt32(MSP_YEAR);
                else
                    entity.Year = null;
                entity.Flag = MSP_FLAG;
                var DomainName = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build().GetSection("CHRIS_REPORTING")["API_URL"];
                string BASE_URL = DomainName + "api/PayrollReporting/MonthlyStaffPaymentListings/";
                using (HttpClient clienFNREP08 = new HttpClient())
                {
                    using (HttpRequestMessage req310 = new HttpRequestMessage(HttpMethod.Post, BASE_URL))
                    {
                        req310.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                        string dataAsJson = System.Text.Json.JsonSerializer.Serialize(entity,
                        new JsonSerializerOptions() { WriteIndented = false });
                        message += dataAsJson + Environment.NewLine;
                        var content = new StringContent(dataAsJson, Encoding.UTF8, "application/json");
                        req310.Content = content;
                        req310.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                        HttpResponseMessage response = clienFNREP08.SendAsync(req310).Result;
                        int StatusCode = (int)response.StatusCode;
                        string StatusDesc = response.StatusCode.ToString();
                        if (StatusCode == 200)
                        {
                            file = response;
                            return File(file.Content.ReadAsByteArrayAsync().Result, "application/octet-stream", "PY002_" + DateTime.Now.ToString("dd_MM_yyyy") + ".pdf");
                        }
                        else
                        {
                            message = "Code : " + StatusCode + " | Description : " + StatusDesc;
                            return View();
                        }
                        //return responsse;
                    }
                }
            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            finally
            {
                ViewBag.message = message;
            }
            return View();
        }
        #endregion

        #region PROVIDENT FUND REPORT
        public IActionResult ProvidentFundReport()
        {
            string message = "";
            try
            {

            }
            catch (Exception ex)
            {
                message = ex.Message;
            }
            finally
            {
                ViewBag.message = message;
            }
            return View();
        }
        [HttpPost]
        public IActionResult ProvidentFundReport(string PFR_BRANCH, string PFR_SEGMENT, string PFR_CATEGORY, int? PFR_MONTH, int? PFR_YEAR)
        {
            string message = "";
            try
            {
                HttpResponseMessage file = new HttpResponseMessage();
                PY003Model entity = new PY003Model();
                entity.Branch = PFR_BRANCH;
                entity.Segment = PFR_SEGMENT;
                entity.Category = PFR_CATEGORY;
                if (PFR_MONTH != null)
                    entity.Month = Convert.ToInt32(PFR_MONTH);
                else
                    entity.Month = null;
                if (PFR_YEAR != null)
                    entity.Year = Convert.ToInt32(PFR_YEAR);
                else
                    entity.Year = null;
                var DomainName = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build().GetSection("CHRIS_REPORTING")["API_URL"];
                string BASE_URL = DomainName + "api/PayrollReporting/ProvidentFundReport/";
                using (HttpClient clienFNREP08 = new HttpClient())
                {
                    using (HttpRequestMessage req310 = new HttpRequestMessage(HttpMethod.Post, BASE_URL))
                    {
                        req310.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                        string dataAsJson = System.Text.Json.JsonSerializer.Serialize(entity,
                        new JsonSerializerOptions() { WriteIndented = false });
                        message += dataAsJson + Environment.NewLine;
                        var content = new StringContent(dataAsJson, Encoding.UTF8, "application/json");
                        req310.Content = content;
                        req310.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                        HttpResponseMessage response = clienFNREP08.SendAsync(req310).Result;
                        int StatusCode = (int)response.StatusCode;
                        string StatusDesc = response.StatusCode.ToString();
                        if (StatusCode == 200)
                        {
                            file = response;

CHRIS/CHRIS/Views/PayrollReports/ActurialReportDownload.cshtml
@{
    ViewBag.Title = "Acturial Report Download";
    ViewBag.Controller = "Home";
    ViewBag.Action = "Acturial Report Download";
}

<div class="card card-primary card-outline">
    <div class="card-header">
        <h3 class="card-title">Report Parameters</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
        </div>
    </div>
    <!-- /.Case Form Start -->
    <div class="card-body">
        <div class="row">

            <div class="col-md-3">
                <div class="form-group">
                    @Html.Label("Desname")
                    <div class="col-md-12">
                        <input class="form-control" id="Desname" />
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    @Html.Label("Enter Branch or ALL")
                    <div class="col-md-12">
                        <input class="form-control" id="wbranch" />
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    @Html.Label("ENTER GF/GCB")
                    <div class="col-md-12">
                        <input class="form-control" id="wseg" />
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    @Html.Label("[C]=Clerks [Blank]=Officer ")
                    <div class="col-md-12">
                        <input class="form-control" id="w_cate" />
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    @Html.Label("Enter Date")
                    <div class="col-md-12">
                        <input class="form-control" id="wdate" type="date" />
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" name="RunActurialReportDownload" value="Run" class="btn btn-outline-primary" />
        </div>
    </div>
</div>

CHRIS/CHRIS/Views/PayrollReports/Annual10CPaymentReport.cshtml
@{
    ViewBag.Title = "Annual 10C Payment Report";
    ViewBag.Controller = "Home";
    ViewBag.Action = "Annual 10C PaymentReport";
    if (ViewBag.message != "")
    {
        <div class="alert alert-warning text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span class="fas fa-times"></span></button>
            @ViewBag.message
        </div>
    }
}
@using (Html.BeginForm("Annual10CPaymentReport", "PayrollReports", FormMethod.Post))
{
    <div class="card card-primary card-outline">
        <div class="card-header">
            <h3 class="card-title">Report Parameters</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
        </div>
        <!-- /.Case Form Start -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Enter Branch or ALL")
                        <div class="col-md-12">
                            <input class="form-control" id="ABR_BRANCH" name="ABR_BRANCH" maxlength="3" />
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Enter Year")
                        <div class="col-md-12">
                            <input class="form-control" id="ABR_YEAR" name="ABR_YEAR" maxlength="4" />
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Enter Segment")
                        <div class="col-md-12">
                            <input class="form-control" id="ABR_SEGMENT" name="ABR_SEGMENT" maxlength="3"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="RunAnnual10CPaymentReport" value="Run" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}

CHRIS/CHRIS/Views/PayrollReports/MonthlySalaryInter.cshtml
@{
    ViewBag.Title = "Monthly Salary Inter";
    ViewBag.Controller = "Home";
    ViewBag.Action = "Monthly Salary Inter";
    if (ViewBag.message != "")
    {
        <div class="alert alert-warning text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span class="fas fa-times"></span></button>
            @ViewBag.message
        </div>
    }
}
@using (Html.BeginForm("MonthlySalaryInter", "PayrollReports", FormMethod.Post))
{
    <div class="card card-primary card-outline">
        <div class="card-header">
            <h3 class="card-title">Report Parameters</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Enter Valid Branch")
                        <div class="col-md-12">
                            <input class="form-control" id="MSI_BRANCH" name="MSI_BRANCH" maxlength="3" />
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Month")
                        <div class="col-md-12">
                            <input class="form-control" id="MSI_MONTH" name="MSI_MONTH" maxlength="2" type="number" />
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Year")
                        <div class="col-md-12">
                            <input class="form-control" id="MSI_YEAR" name="MSI_YEAR" maxlength="4" type="number" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="RunMonthlySalaryInter" value="Run" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}

CHRIS/CHRIS/Views/PayrollReports/MonthlyStaffPaymentListings.cshtml
@{
    ViewBag.Title = "Monthly Staff Payment Listings";
    ViewBag.Controller = "Home";
    ViewBag.Action = "Monthly Staff Payment Listings";
    if (ViewBag.message != "")
    {
        <div class="alert alert-warning text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span class="fas fa-times"></span></button>
            @ViewBag.message
        </div>
    }
}
@using (Html.BeginForm("MonthlyStaffPaymentListings", "PayrollReports", FormMethod.Post))
{
    <div class="card card-primary card-outline">
        <div class="card-header">
            <h3 class="card-title">Report Parameters</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
        </div>
        <!-- /.Case Form Start -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Enter Valid Branch")
                        <div class="col-md-12">
                            <select class="form-control" style="width: 100%;" id="MSP_BRANCH" name="MSP_BRANCH">
                                <option>KHI</option>
                                <option>LHR</option>
                                <option>RWP</option>
                                <option>FBD</option>
                                <option>ISL</option>
                                <option>SLK</option>
                                <option>MLT</option>
                                <option>HYD</option>
                                <option>GUJ</option>
                                <option>JHL</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Enter Valid Segment")
                        <div class="col-md-12">
                            <input class="form-control" id="MSP_SEGMENT" name="MSP_SEGMENT" />
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Enter Catagory or null")
                        <div class="col-md-12">
                            <input class="form-control" id="MSP_CATEGORY" name="MSP_CATEGORY" />
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Enter Month")
                        <div class="col-md-12">
                            <input class="form-control" id="MSP_MONTH" name="MSP_MONTH" />
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Enter Year")
                        <div class="col-md-12">
                            <input class="form-control" id="MSP_YEAR" name="MSP_YEAR" />
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.Label("Enter Confirmation (Y/N)")
                        <div class="col-md-12">
                            <input class="form-control" id="MSP_FLAG" name="MSP_FLAG" maxlength="1" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="RunMonthlyStaffPaymentListings" value="Run" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}

CHRIS/CHRIS/Views/PayrollReports/OverTimeReport.cshtml
@{
    ViewBag.Title = "OverTime Report";
    ViewBag.Controller = "Home";
    ViewBag.Action = "Overtime Report";
    if (ViewBag.message != "")
    {
        <div class="alert alert-warning text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span class="fas fa-times"></span></button>
            @ViewBag.message
        </div>
    }
}
@using (Html.BeginForm("OverTimeReport", "PayrollReports", FormMethod.Post))
{
    <div class="card card-primary card-outline">
        <div class="card-header">
            <h3 class="card-title">Report Parameters</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
        </div>
        <!-- /.Case Form Start -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Valid Branch")
                        <div class="col-md-12">
                            <input class="form-control" id="OTR_BRANCH" name="OTR_BRANCH" maxlength="3" />
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Valid Segment")
                        <div class="col-md-12">
                            <input class="form-control" id="OTR_SEGMENT" name="OTR_SEGMENT" maxlength="3" />
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Month (MM)")
                        <div class="col-md-12">
                            <input class="form-control" type="number" id="OTR_MONTH" name="OTR_MONTH" maxlength="2" />
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Year")
                        <div class="col-md-12">
                            <input class="form-control" type="number" id="OTR_YEAR" name="OTR_YEAR" maxlength="4" />
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Catagory or null")
                        <div class="col-md-12">
                            <input class="form-control" id="OTR_CATEGORY" name="OTR_CATEGORY" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="RunOvertimeReport" value="Run" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}

CHRIS/CHRIS/Views/PayrollReports/ProvidentFundReport.cshtml
@{
    ViewBag.Title = "Provident Fund Report";
    ViewBag.Controller = "Home";
    ViewBag.Action = "Provident Fund Report";
    if (ViewBag.message != "")
    {
        <div class="alert alert-warning text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span class="fas fa-times"></span></button>
            @ViewBag.message
        </div>
    }
}
@using (Html.BeginForm("ProvidentFundReport", "PayrollReports", FormMethod.Post))
{
    <div class="card card-primary card-outline">
        <div class="card-header">
            <h3 class="card-title">Report Parameters</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
        </div>
        <!-- /.Case Form Start -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Valid Branch")
                        <div class="col-md-12">
                            <input class="form-control" id="PFR_BRANCH" name="PFR_BRANCH" maxlenght="3"/>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Valid Segment")
                        <div class="col-md-12">
                            <input class="form-control" id="PFR_SEGMENT" name="PFR_SEGMENT" />
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Month")
                        <div class="col-md-12">
                            <input class="form-control" id="PFR_MONTH" name="PFR_MONTH" />
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Year")
                        <div class="col-md-12">
                            <input class="form-control" id="PFR_YEAR" name="PFR_YEAR" />
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Catagory or null")
                        <div class="col-md-12">
                            <input class="form-control" id="PFR_CATEGORY" name="PFR_CATEGORY" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="RunPeriodicReportForIncPromotion" value="Run" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}

CHRIS/CHRIS/Views/PayrollReports/ReconcilimentReport.cshtml
@{
    ViewBag.Title = "Reconciliment Report";
    ViewBag.Controller = "Home";
    ViewBag.Action = "Reconciliment Report";
    if (ViewBag.message != "")
    {
        <div class="alert alert-warning text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span class="fas fa-times"></span></button>
            @ViewBag.message
        </div>
    }
}
@using (Html.BeginForm("ReconcilimentReport", "PayrollReports", FormMethod.Post))
{
    <div class="card card-primary card-outline">
        <div class="card-header">
            <h3 class="card-title">Report Parameters</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
            </div>
        </div>
        <!-- /.Case Form Start -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Valid Branch")
                        <div class="col-md-12">
                            <select class="form-control select2" style="width: 100%;" id="RR_BRANCH" name="RR_BRANCH">
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Valid Segment")
                        <div class="col-md-12">
                            <select class="form-control" style="width: 100%;" id="SWR_SEGMENT" name="SWR_SEGMENT">
                                <option>GF</option>
                                <option>GCB</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Month")
                        <div class="col-md-12">
                            <input class="form-control" type="number" id="RR_MONTH" name="RR_MONTH" maxlength="2" />
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Year")
                        <div class="col-md-12">
                            <select class="form-control" style="width: 100%;" id="RR_YEAR" name="RR_YEAR">
                                @{
                                    string Year = DateTime.Now.Year.ToString();
                                }
                                <option>2010</option>
                                <option>@Year</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @Html.Label("Enter Category or Null")
                        <div class="col-md-12">
                            <input class="form-control" id="RR_CATEGORY" name="RR_CATEGORY" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="RunReconcilimentReport" value="Run" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}